# Generated by Django 5.2.8 on 2026-05-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0007_settings_payment_and_form_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='allow_installments',
            field=models.BooleanField(
                default=True,
                help_text='Quando desmarcado, o cupom só pode ser usado em pagamentos à vista',
                verbose_name='Permitir uso em parcelado',
            ),
        ),
        migrations.AddField(
            model_name='coupon',
            name='allowed_payment_methods',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Deixe vazio para permitir todas as formas de pagamento',
                verbose_name='Formas de Pagamento Permitidas',
            ),
        ),
        migrations.AddField(
            model_name='settings',
            name='enable_coupons',
            field=models.BooleanField(
                default=True,
                help_text='Controla a disponibilidade global de cupons para novas inscrições',
                verbose_name='Permitir Cupons',
            ),
        ),
    ]
