# Generated by Django 5.0.1 on 2026-06-18 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_make_bank_details_optional_for_direct_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='Descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Valor')),
                ('source_type', models.CharField(choices=[('OFFERING', 'Oferta'), ('INVESTOR', 'Investidor'), ('DONATION', 'Doação'), ('OTHER', 'Outro')], default='OTHER', max_length=20, verbose_name='Origem')),
                ('date', models.DateField(verbose_name='Data')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Aporte Financeiro',
                'verbose_name_plural': 'Aportes Financeiros',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='expenserequest',
            new_name='finance_exp_area_id_906453_idx',
            old_name='finance_exp_area_st_5f3935_idx',
        ),
        migrations.RenameIndex(
            model_name='expenserequest',
            new_name='finance_exp_rubric__5bf901_idx',
            old_name='finance_exp_rubric__ea4bb6_idx',
        ),
        migrations.RenameIndex(
            model_name='expenserequest',
            new_name='finance_exp_request_54507b_idx',
            old_name='finance_exp_request_1eb367_idx',
        ),
    ]
