# Generated by Django 5.0.1 on 2026-07-03 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0011_supplier_calendar"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="supplierpayment",
            new_name="finance_sup_schedul_90ff47_idx",
            old_name="finance_sup_scheduled_95b15a_idx",
        ),
        migrations.RenameIndex(
            model_name="supplierpayment",
            new_name="finance_sup_expense_90a28c_idx",
            old_name="finance_sup_request_896353_idx",
        ),
        migrations.RenameIndex(
            model_name="supplierpayment",
            new_name="finance_sup_supplie_a8958d_idx",
            old_name="finance_sup_supplier_496653_idx",
        ),
        migrations.AlterField(
            model_name="expenseauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATED", "Criada"),
                    ("UPDATED", "Atualizada"),
                    ("UNDER_REVIEW", "Em análise"),
                    ("APPROVED", "Aprovada"),
                    ("REJECTED", "Rejeitada"),
                    ("CANCELLED", "Cancelada"),
                    ("EXECUTED", "Executada"),
                    ("ATTACHMENT_ADDED", "Anexo adicionado"),
                    ("ATTACHMENT_REPLACED", "Anexo substituído"),
                    ("ATTACHMENT_REMOVED", "Anexo removido"),
                    ("ADVANCE_SETTLEMENT_SUBMITTED", "Prestação enviada"),
                    ("ADVANCE_RETURN_CONFIRMED", "Devolução confirmada"),
                    ("ADVANCE_MANUALLY_CLOSED", "Encerrado manualmente"),
                    ("SUPPLIER_PAYMENT_SCHEDULED", "Pagamento de fornecedor agendado"),
                    ("SUPPLIER_PAYMENT_UPDATED", "Pagamento de fornecedor atualizado"),
                    (
                        "SUPPLIER_PAYMENT_PAID",
                        "Pagamento de fornecedor marcado como pago",
                    ),
                ],
                max_length=32,
                verbose_name="Ação",
            ),
        ),
    ]
