# Generated by Django 5.2.8 on 2026-05-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_merge_20251113_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='is_visible_on_site',
            field=models.BooleanField(
                default=False,
                help_text='Define o lote exibido no frontend quando houver múltiplos lotes elegíveis',
                verbose_name='Visível no site',
            ),
        ),
    ]
